export type AdminSection =
  | "overview"
  | "programme"
  | "phases"
  | "themes"
  | "map"
  | "points"
  | "jackpot"
  | "rewards"
  | "reward-games"
  | "challenges"
  | "attempts"
  | "players"
  | "community"
  | "attendance"
  | "audit";